apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "firecrawl.fullname" . }}-config
  labels:
    {{- include "firecrawl.labels" . | nindent 4 }}
data:
  HOST: {{ .Values.config.host | quote }}
  {{- $fullname := include "firecrawl.fullname" . }}
  {{- $redisUrl := .Values.config.redisUrl }}
  {{- if and (not $redisUrl) .Values.redis.enabled }}
    {{- $redisUrl = printf "redis://%s-redis:%d" $fullname .Values.redis.service.port }}
  {{- end }}
  REDIS_URL: {{ $redisUrl | quote }}
  {{- $redisRateLimitUrl := .Values.config.redisRateLimitUrl }}
  {{- if and (not $redisRateLimitUrl) .Values.redis.enabled }}
    {{- $redisRateLimitUrl = printf "redis://%s-redis:%d" $fullname .Values.redis.service.port }}
  {{- end }}
  REDIS_RATE_LIMIT_URL: {{ $redisRateLimitUrl | quote }}
  {{- $playwrightUrl := .Values.config.playwrightUrl }}
  {{- if and (not $playwrightUrl) .Values.playwright.enabled }}
    {{- $playwrightUrl = printf "http://%s-playwright:%d" $fullname .Values.playwright.service.port }}
  {{- end }}
  PLAYWRIGHT_MICROSERVICE_URL: {{ $playwrightUrl | quote }}
  USE_DB_AUTHENTICATION: {{ .Values.config.useDbAuthentication | quote }}
  SENTRY_ENVIRONMENT: {{ .Values.config.sentryEnvironment | quote }}
  ENV: {{ .Values.config.env | quote }}
  LOGGING_LEVEL: {{ .Values.config.loggingLevel | quote }}
  IS_KUBERNETES: "true"
{{- with .Values.extraConfig }}
{{ toYaml . | indent 2 }}
{{- end }}
