{{- if .Values.playwright.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "firecrawl.fullname" . }}-playwright
  labels:
    {{- include "firecrawl.labels" . | nindent 4 }}
    app.kubernetes.io/component: playwright
spec:
  replicas: {{ .Values.playwright.replicaCount }}
  selector:
    matchLabels:
      {{- include "firecrawl.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: playwright
  template:
    metadata:
      labels:
        {{- include "firecrawl.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: playwright
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: playwright-service
          image: "{{ .Values.playwright.image.repository }}:{{ .Values.playwright.image.tag }}"
          imagePullPolicy: {{ .Values.playwright.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.playwright.port }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.playwright.port | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- toYaml .Values.playwright.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "firecrawl.fullname" . }}-playwright
  labels:
    {{- include "firecrawl.labels" . | nindent 4 }}
    app.kubernetes.io/component: playwright
spec:
  type: {{ .Values.playwright.service.type }}
  ports:
    - port: {{ .Values.playwright.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "firecrawl.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: playwright
{{- end }}
